### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by Pillow-Fan** [Magisk-Modules-Repo/ad_gestures#2]
The module was installed successfully on an 8.0.0 OxygeOS stock ROM on a OnePlus 3T device wich supports ambient display but the gestures won't work.
Are they overwritten by the stock lift-up Ambient display?

**Comment by ronell1292k** [comment]
Definitely is the case. I'd advise against using it on OOS or any skins as far as possible. Apologies for the late reply.
